/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SearchRouteImport } from './app/search'
import { Route as IndexRouteImport } from './app/index'
import { Route as ProfileIndexRouteImport } from './app/profile/index'
import { Route as EventsIndexRouteImport } from './app/events/index'
import { Route as ProfileSettingsRouteImport } from './app/profile/settings'
import { Route as ProfileBookingsRouteImport } from './app/profile/bookings'
import { Route as OrganizerDashboardRouteImport } from './app/organizer/dashboard'
import { Route as EventsSlugRouteImport } from './app/events/$slug'
import { Route as BookingSummaryRouteImport } from './app/booking/summary'
import { Route as BookingSeatsRouteImport } from './app/booking/seats'
import { Route as BookingConfirmationRouteImport } from './app/booking/confirmation'
import { Route as AuthRegisterRouteImport } from './app/auth/register'
import { Route as AuthLoginRouteImport } from './app/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './app/auth/forgot-password'
import { Route as AdminDashboardRouteImport } from './app/admin/dashboard'
import { Route as EventsSlugShowsRouteImport } from './app/events/$slug.shows'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileBookingsRoute = ProfileBookingsRouteImport.update({
  id: '/profile/bookings',
  path: '/profile/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/organizer/dashboard',
  path: '/organizer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSummaryRoute = BookingSummaryRouteImport.update({
  id: '/booking/summary',
  path: '/booking/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSeatsRoute = BookingSeatsRouteImport.update({
  id: '/booking/seats',
  path: '/booking/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugShowsRoute = EventsSlugShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => EventsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/seats': typeof BookingSeatsRoute
  '/booking/summary': typeof BookingSummaryRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/events/': typeof EventsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/events/$slug/shows': typeof EventsSlugShowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/seats': typeof BookingSeatsRoute
  '/booking/summary': typeof BookingSummaryRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/events': typeof EventsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/events/$slug/shows': typeof EventsSlugShowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/seats': typeof BookingSeatsRoute
  '/booking/summary': typeof BookingSummaryRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/events/': typeof EventsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/events/$slug/shows': typeof EventsSlugShowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/admin/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/booking/confirmation'
    | '/booking/seats'
    | '/booking/summary'
    | '/events/$slug'
    | '/organizer/dashboard'
    | '/profile/bookings'
    | '/profile/settings'
    | '/events/'
    | '/profile/'
    | '/events/$slug/shows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/admin/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/booking/confirmation'
    | '/booking/seats'
    | '/booking/summary'
    | '/events/$slug'
    | '/organizer/dashboard'
    | '/profile/bookings'
    | '/profile/settings'
    | '/events'
    | '/profile'
    | '/events/$slug/shows'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/admin/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/booking/confirmation'
    | '/booking/seats'
    | '/booking/summary'
    | '/events/$slug'
    | '/organizer/dashboard'
    | '/profile/bookings'
    | '/profile/settings'
    | '/events/'
    | '/profile/'
    | '/events/$slug/shows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  BookingSeatsRoute: typeof BookingSeatsRoute
  BookingSummaryRoute: typeof BookingSummaryRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  ProfileBookingsRoute: typeof ProfileBookingsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/bookings': {
      id: '/profile/bookings'
      path: '/profile/bookings'
      fullPath: '/profile/bookings'
      preLoaderRoute: typeof ProfileBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/dashboard': {
      id: '/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/summary': {
      id: '/booking/summary'
      path: '/booking/summary'
      fullPath: '/booking/summary'
      preLoaderRoute: typeof BookingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/seats': {
      id: '/booking/seats'
      path: '/booking/seats'
      fullPath: '/booking/seats'
      preLoaderRoute: typeof BookingSeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/shows': {
      id: '/events/$slug/shows'
      path: '/shows'
      fullPath: '/events/$slug/shows'
      preLoaderRoute: typeof EventsSlugShowsRouteImport
      parentRoute: typeof EventsSlugRoute
    }
  }
}

interface EventsSlugRouteChildren {
  EventsSlugShowsRoute: typeof EventsSlugShowsRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugShowsRoute: EventsSlugShowsRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  BookingSeatsRoute: BookingSeatsRoute,
  BookingSummaryRoute: BookingSummaryRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  ProfileBookingsRoute: ProfileBookingsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  EventsIndexRoute: EventsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
